#!/usr/bin/bash
# bash url_processing.sh google_urls google_dump.txt urls_txt urls_processing_cn.py tokens.txt
# freq_bash.txt gap1.txt gap2.txt out.txt

lynx -dump $1 > $2
egrep " +[0-9]+\. https.+$" $2 | cut -d"=" -f2 | cut -d"&" -f1 | egrep "^https.+$" > $3
python '$4' > $5
tr " " "\n" < $5 | sort -fg | uniq -ic | uniq -c | sort -rg > $6;
tail -n +2 $6 > $7;
tail -n +3 $6 > $8;
paste $5 $6 $7 > $9;
